services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: myHibernate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: expo
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: 36d973de3113
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/myHibernate
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: expo

volumes:
  postgres_data: